spring:
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: root
  h2:
    console:
      enabled: true
  security:
    jwt:
      secret-key: alxymgIK7vsMoUYiajiC7IvyLyk5DRSz  # will be replaced with different key
      access-token-expiration: 3600      # 1 hour
      refresh-token-expiration: 604800   # 1 week
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always
  data:
    redis:
      host: redis
      port: 6379