name: KBuddy-server Jenkins

on:
  push:
    branches:
      - main

jobs:
  jenkins:
    name: Jenkins-action
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "K-Buddy Server"