name: KBuddy-server Jenkins


on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"  # 버전 태그를 달아 배포할 때 사용할 태그 필드
  pull_request:
    types:
      - closed

jobs:
  build-server-image:
    if: github.event.pull_request.merged == true
    name: Build on ARM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > src/main/resources/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> src/main/resources/.env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> src/main/resources/.env
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> src/main/resources/.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> src/main/resources/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            kbuddydev/k-buddy_server
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  post-slack:
    if: github.event.pull_request.merged == true
    name: Post CI result to a Slack channel
    runs-on: ubuntu-latest
    needs: build-server-image
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'notification'
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


  trigger-jenkins:
    if: github.event.pull_request.merged == true
    name: Jenkins-action
    runs-on: ubuntu-latest
    needs: build-server-image
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "K-Buddy Server"
